# Generated by Django 4.2.16 on 2025-01-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_developer_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='fotos',
            field=models.ImageField(upload_to='portafolio/'),
        ),
    ]
