# Generated by Django 4.2.16 on 2025-01-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_developer_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='developer',
            name='github',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
